### ISSUE TITLE
How am I supposed to include it in my Juce project?

### ISSUE THREAD

**Issue by JessyJP** [SoundDevelopment/sound_meter#2]
There are no instructions how it's supposed to be integrated.  
Module? etc?
It can't resolve the juce dependencies so I tried to manually resolve all the header dependencies but then even though it complied, it still couldn't resolve the MeterComponenet once the constructor was called in the editor.

**Comment by SoundDevelopment** [comment]
Yes. It's a JUCE module.
The instructions are in the readme as well as a demo project.
Just make sure the module folder is called "sound_meter".

**Comment by JessyJP** [comment]
Is it possible to flip it horizontally ?

**Comment by SoundDevelopment** [comment]
Not at the moment, but it's a good idea.
Hope to add that soon.
